import { createElement } from 'lwc';
import EngDashCasesClosedLast30 from 'c/engDashCasesClosedLast30';

describe('c-eng-dash-cases-closed-last30', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-eng-dash-cases-closed-last30', {
            is: EngDashCasesClosedLast30
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});